name: Build and Deploy Wheels

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python version to use'
        required: true
        type: choice
        options:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
        default: '3.12'
      package_name:
        description: 'Package name to build'
        required: true
        type: choice
        options:
          - numpy
          - scipy
          - shapely
          - google-crc32c
          - grpcio
          - fastapi
          - pymongo
          - sentence-transformers
          - nltk
          - torch
          - python-crfsuite
          - regex
          - biotite
          - tiktoken
      custom_package_name:
        description: 'Custom package name to build (if set, overrides package_name)'
        required: false
        type: string
      package_version:
        description: 'Package version to build'
        required: true

jobs:
  build-wheels:
    runs-on: ubuntu-latest
    name: ${{ matrix.platform }} ${{ matrix.arch }} ${{ github.event.inputs.package_name }} ${{ github.event.inputs.package_version }} on Python ${{ github.event.inputs.python_version }}
    strategy:
      matrix:
        arch: [arm64, amd64]
        platform: [debian, alpine]
    env:
      SOURCE_DATE_EPOCH: 1690000000  # Fixed timestamp for reproducibility
      PYTHONHASHSEED: 0  # Ensure deterministic builds
    steps:
      - name: Print input values
        run: |
          echo "Python Version: ${{ github.event.inputs.python_version }}"
          echo "Package Name: ${{ github.event.inputs.package_name }}"
          echo "Custom Package Name: ${{ github.event.inputs.custom_package_name }}"          
          echo "Package Version: ${{ github.event.inputs.package_version }}"
          echo "SOURCE_DATE_EPOCH: $SOURCE_DATE_EPOCH"
          echo "PYTHONHASHSEED: $PYTHONHASHSEED"

      - name: Determine Package Name
        id: package-name
        run: |
          if [ -n "${{ github.event.inputs.custom_package_name }}" ]; then
            echo "PACKAGE_NAME=${{ github.event.inputs.custom_package_name }}" >> $GITHUB_ENV
          else
            echo "PACKAGE_NAME=${{ github.event.inputs.package_name }}" >> $GITHUB_ENV
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull binfmt image
        run: docker pull docker.io/tonistiigi/binfmt:qemu-v6.2.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Package Wheel
        run: |
          if [ "${{ matrix.platform }}" = "alpine" ]; then
            PACKAGE_DOCKERFILE="packages/${{ env.PACKAGE_NAME }}/alpine.Dockerfile"
            if [ ! -f "$PACKAGE_DOCKERFILE" ]; then
              PACKAGE_DOCKERFILE="packages/default/alpine.Dockerfile"
            fi
          else
            PACKAGE_DOCKERFILE="packages/${{ env.PACKAGE_NAME }}/Dockerfile"
            if [ ! -f "$PACKAGE_DOCKERFILE" ]; then
              PACKAGE_DOCKERFILE="packages/default/Dockerfile"
            fi
          fi
          docker buildx build --platform linux/${{ matrix.arch }} \
          --build-arg PACKAGE_NAME=${{ env.PACKAGE_NAME }} \
          --build-arg PACKAGE_VERSION=${{ github.event.inputs.package_version }} \
          --build-arg PYTHON_VERSION=${{ github.event.inputs.python_version }} \
          --build-arg SOURCE_DATE_EPOCH=${{ fromJSON(env.SOURCE_DATE_EPOCH) }} \
          --build-arg PYTHONHASHSEED=${{ fromJSON(env.PYTHONHASHSEED) }} \
          -f $PACKAGE_DOCKERFILE \
          -t my-${{ env.PACKAGE_NAME }}-builder:latest \
          --output type=local,dest=./wheels_output .

      - name: Persist wheels directory
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.platform }}-${{ matrix.arch }}
          path: ./wheels_output/wheels/*.whl  # Only upload wheel files
          if-no-files-found: error

      - name: Hash Alpine wheels
        run: |
          find ./wheels_output -name "${{ env.PACKAGE_NAME }}*.whl" -exec sha256sum {} + > alpine_wheels.sha256


  upload-wheels:
    runs-on: ubuntu-latest
    needs: build-wheels
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set PACKAGE_NAME
        run: |
          if [ -n "${{ github.event.inputs.custom_package_name }}" ]; then
            echo "PACKAGE_NAME=${{ github.event.inputs.custom_package_name }}" >> $GITHUB_ENV
          else
            echo "PACKAGE_NAME=${{ github.event.inputs.package_name }}" >> $GITHUB_ENV
          fi

      - name: Download ${{ env.PACKAGE_NAME }} Wheels Artifact
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          merge-multiple: true
          path: ./wheels

#      - name: Unpack the wheels
#        run: |
#          pip install wheel
#          for file in ./wheels/*.whl; do
#            wheel unpack "$file"
#          done
#          for file in ./wheels/*.whl; do
#            echo "Contents of $file:"
#            unzip -l "$file"
#            unzip -d "${file%.whl}" "$file"
#            echo "Unpacked contents:"
#            ls -R "${file%.whl}"
#            echo "-----------------------------"
#          done
#          # Delete the unpacked folder
#          rm -rf "${file%.whl}"


      - name: Install Git LFS
        run: |
          git lfs install

      - name: Upload wheels to GitHub Pages
        run: |
          set +x
          ls -haltR .
          mkdir -p docs/${{ env.PACKAGE_NAME }}
          mv -f wheels/* docs/${{ env.PACKAGE_NAME }}/
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add docs/
          git commit -m "Add wheels for ${{ env.PACKAGE_NAME }} ${{ github.event.inputs.package_version }}"
          git pull --rebase origin main  # Pull the latest changes and rebase
          if [ "$(git diff --stat origin/main)" != "" ]; then
            git push
          else
            echo "No changes to push"
          fi

      - name: Update index.html
        run: |
          set +x
          cd docs/
          # Generate the root index.html
          echo "<html><body><ul>" > index.html
          for package in $(ls -d */); do
            package_name=${package%/}
            echo "<li><a href=\"$package_name/\">$package_name</a></li>" >> index.html
      
            # Generate index.html for each package
            mkdir -p "$package_name"
            echo "<html><body><h1>$package_name</h1><ul>" > "$package_name/index.html"
            for package_file in $(ls "${package_name}/"*.whl 2>/dev/null); do
             # Only include .whl files
              file_name=$(basename "$package_file")
              echo "<li><a href=\"https://github.com/imranq2/alpine-wheels/raw/main/docs/$package_name/$file_name\">$file_name</a></li>" >> "$package_name/index.html"
            done
            echo "</ul></body></html>" >> "$package_name/index.html"
          done
          echo "</ul></body></html>" >> index.html
      
          git add index.html */index.html

          # Check if there are any changes before committing
          if ! git diff --cached --quiet; then
            git commit -m "Update package index files"
            git push
          else
            echo "No changes to commit"
          fi
